packages:
  - .
  # - '../first-class-families'
  # - extra-dep: true
  #   location:
  #     git: https://github.com/Lysxia/first-class-families.git
  #     commit: 80f6c860ab4d08e85b872494c48fff121025255c
resolver: lts-16.31

extra-deps:
  # - aeson-1.3.1.1
  - aeson-lens-0.5.0.0
  # - indexed-0.1.3
  # - do-notation-0.1.0.1
  # - inspection-testing-0.3
